name: GitHub Breakout Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Breakout (dark)
        uses: cyprieng/github-breakout@v1
        with:
          github_username: ${{ github.repository_owner }}
          theme: dark
          output_path: assets/breakout-dark.svg

      - name: Generate GitHub Breakout (light)
        uses: cyprieng/github-breakout@v1
        with:
          github_username: ${{ github.repository_owner }}
          theme: light
          output_path: assets/breakout-light.svg

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Breakout game"
